---
- name: Add Grafana APT repository
  become: true
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  become: true
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present

- name: Update APT cache
  become: true
  apt:
    update_cache: yes

- name: Install Grafana
  become: true
  apt:
    name: grafana
    state: present

- name: Enable and start Grafana service
  become: true
  systemd:
    name: grafana-server
    enabled: yes
    state: started
